DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `CHECK_EXISTS_SOUNDS`(IN `MYARTIST` VARCHAR(255))
SELECT 1 AS `exists` FROM SONGS WHERE ARTIST=MYARTIST$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `DELETE_ARTIST`(IN `MYARTIST` VARCHAR(255))
DELETE FROM IMAGES WHERE ARTIST=MYARTIST$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `DELETE_MUSIC`(IN `MYID` INT)
DELETE FROM SONGS WHERE ID=MYID$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `GET_AUDIO`(IN `MYID` VARCHAR(255))
SELECT audio_path FROM SONGS WHERE ID = MYID$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `GET_IMAGE`(IN `MYARTIST` VARCHAR(255))
SELECT image_path FROM IMAGES WHERE ARTIST = MYARTIST$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `GET_SONGS`()
SELECT songs.*, images.image FROM SONGS LEFT JOIN images on songs.artist=images.artist order by name ASC$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT_MUSIC`(IN `MYNAME` VARCHAR(255), IN `MYARTIST` VARCHAR(255), IN `MYYEAR` YEAR, IN `MYAUDIO` VARCHAR(255), IN `MYIMG` VARCHAR(255), IN `MYAUDIO_PATH` VARCHAR(255), IN `MYIMG_PATH` VARCHAR(255))
BEGIN
IF (MYIMG IS NOT NULL OR MYIMG !="") THEN 

	IF (SELECT 1 FROM IMAGES WHERE ARTIST=MYARTIST) THEN
    
		UPDATE IMAGES SET IMAGE=MYIMG, IMAGE_PATH=MYIMG_PATH WHERE ARTIST=MYARTIST;
        
	ELSE
    
		INSERT INTO IMAGES (`ARTIST`,`IMAGE`,`IMAGE_PATH`) VALUES (MYARTIST,MYIMG,MYIMG_PATH);
     
	END IF;

ELSE
	
    INSERT INTO IMAGES (ARTIST) VALUES(MYARTIST);
    
END IF;


INSERT INTO SONGS (`NAME`,`ARTIST`,`YEAR`,`AUDIO`,`AUDIO_PATH`)  VALUES (MYNAME, MYARTIST, MYYEAR, MYAUDIO, MYAUDIO_PATH);
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `UPDATE_MUSIC`(IN `MYID` INT, IN `MYNAME` VARCHAR(255), IN `MYARTIST` VARCHAR(255), IN `MYYEAR` YEAR, IN `MYAUDIO` VARCHAR(255), IN `MYIMG` VARCHAR(255), IN `MYAUDIO_PATH` VARCHAR(255), IN `MYIMG_PATH` VARCHAR(255))
BEGIN 
IF(MYIMG IS NOT NULL OR MYIMG !="") THEN 
	UPDATE IMAGES SET IMAGE=MYIMG, IMAGE_PATH=MYIMG_PATH WHERE ARTIST=MYARTIST;
END IF;

IF( MYAUDIO IS NOT NULL OR MYAUDIO !="") THEN
	UPDATE SONGS SET NAME = MYNAME, `YEAR`=MYYEAR, AUDIO=MYAUDIO, AUDIO_PATH=MYAUDIO_PATH WHERE ID=MYID;
ELSE 
	UPDATE SONGS SET NAME = MYNAME, `YEAR`=MYYEAR WHERE ID=MYID;
END IF;
END$$
DELIMITER ;
